USE [REPORTS]
GO

/****** Object:  View [dbo].[V_KG_EXCEL_BASE]    Script Date: 03.02.2020 16:47:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER VIEW [dbo].[V_KG_EXCEL_BASE] 
AS 
SELECT a.*
	, CASE WHEN CITY_ID = CITY_ID_ANG AND BRANCH_ID = BRANCH_ID_ANG THEN 1
			WHEN BRANCH_ID = BRANCH_ID_ANG THEN 2
			WHEN CITY_ID = CITY_ID_ANG THEN 3
		--	WHEN REGION_ID = REGION_ID_ANG THEN 3
			ELSE NULL END AS BRANCH_FLAG
	, CASE WHEN LOCAL_FAMILY_BUDGET = LOCAL_FAMILY_BUDGET_ANG THEN 1
			WHEN LOCAL_FAMILY_BUDGET2 = LOCAL_FAMILY_BUDGET2_ANG THEN 2
			ELSE NULL END AS BUDG_FLAG
	, CASE WHEN SIZE_OF_POPULATION_TYPE = SIZE_OF_POPULATION_TYPE_ANG THEN 1
			WHEN SIZE_OF_POPULATION_TYPE2 = SIZE_OF_POPULATION_TYPE2_ANG THEN 2
			ELSE NULL END AS POPUL_FLAG
	, CASE WHEN ABS(1.0-(CAST(SALE AS FLOAT) / CAST(SALE_ANG AS FLOAT))) <=0.1 THEN 1	
			WHEN ABS(1.0-(CAST(SALE AS FLOAT) / CAST(SALE_ANG AS FLOAT))) <=0.15 THEN 2
			WHEN ABS(1.0-(CAST(SALE AS FLOAT) / CAST(SALE_ANG AS FLOAT))) <=0.20 THEN 3
			ELSE NULL END AS SALE_FLAG
	, CASE WHEN ABS(1.0-(CAST(SALE AS FLOAT) / CAST(SALE_ANG AS FLOAT))) <=0.1 THEN 1	
			WHEN ABS(1.0-(CAST(SALE AS FLOAT) / CAST(SALE_ANG AS FLOAT))) <=0.15 THEN 2
			WHEN ABS(1.0-(CAST(SALE AS FLOAT) / CAST(SALE_ANG AS FLOAT))) <=0.20 THEN 3
			WHEN ABS(1.0-(CAST(SALE AS FLOAT) / CAST(SALE_ANG AS FLOAT))) <=0.25 THEN 4
			WHEN ABS(1.0-(CAST(SALE AS FLOAT) / CAST(SALE_ANG AS FLOAT))) <=0.30 THEN 5
			ELSE NULL END AS SALE_FLAG_2
	, CASE WHEN ABS(1.0-(CAST(METR AS FLOAT) / CAST(METR_ANG AS FLOAT))) <=0.05 THEN 1 
			WHEN ABS(1.0-(CAST(METR AS FLOAT) / CAST(METR_ANG AS FLOAT))) <=0.1 THEN 2
			WHEN ABS(1.0-(CAST(METR AS FLOAT) / CAST(METR_ANG AS FLOAT))) <=0.15 THEN 3
			ELSE NULL END AS METR_FLAG
	, CASE WHEN ABS(1.0-(CAST(METR AS FLOAT) / CAST(METR_ANG AS FLOAT))) <=0.05 THEN 1 
			WHEN ABS(1.0-(CAST(METR AS FLOAT) / CAST(METR_ANG AS FLOAT))) <=0.1 THEN 2
			WHEN ABS(1.0-(CAST(METR AS FLOAT) / CAST(METR_ANG AS FLOAT))) <=0.15 THEN 3
			WHEN ABS(1.0-(CAST(METR AS FLOAT) / CAST(METR_ANG AS FLOAT))) <=0.20 THEN 4 
			WHEN ABS(1.0-(CAST(METR AS FLOAT) / CAST(METR_ANG AS FLOAT))) <=0.25 THEN 5
			WHEN ABS(1.0-(CAST(METR AS FLOAT) / CAST(METR_ANG AS FLOAT))) <=0.30 THEN 6
			ELSE NULL END AS METR_FLAG_2
	, CASE WHEN COMPETITOR_ID = COMPETITOR_ID_ANG THEN 1
			WHEN COMPETITOR_ID <> COMPETITOR_ID_ANG AND ECHELON_ID = ECHELON_ID_ANG THEN 2
			ELSE NULL END AS COMP_FLAG
	, CASE WHEN HAS_ALCO_LICENCE = HAS_ALCO_LICENCE_ANG THEN 1
			WHEN HAS_ALCO_LICENCE = 0 AND HAS_ALCO_LICENCE_ANG = 1 THEN 2
			ELSE NULL END AS ALCO_FLAG
	, CASE WHEN ABS(1.0-(CAST(SQUARE_TRADE AS FLOAT) / CAST(NULLIF (SQUARE_TRADE_ANG, 0) AS FLOAT))) <=0.05 THEN 1 
			WHEN ABS(1.0-(CAST(SQUARE_TRADE AS FLOAT) / CAST(NULLIF (SQUARE_TRADE_ANG, 0) AS FLOAT))) <=0.1 THEN 2
			WHEN ABS(1.0-(CAST(SQUARE_TRADE AS FLOAT) / CAST(NULLIF (SQUARE_TRADE_ANG, 0) AS FLOAT))) <=0.15 THEN 3
			WHEN ABS(1.0-(CAST(SQUARE_TRADE AS FLOAT) / CAST(NULLIF (SQUARE_TRADE_ANG, 0) AS FLOAT))) <=0.20 THEN 4
			ELSE NULL
			END SQUARE_FLAG
	, CASE WHEN ABS(1.0-(CAST(TRAFIk AS FLOAT) / CAST(TRAFIk_ANG AS FLOAT))) <=0.1 THEN 1 
			WHEN ABS(1.0-(CAST(TRAFIk AS FLOAT) / CAST(TRAFIk_ANG AS FLOAT))) <=0.15 THEN 2
			WHEN ABS(1.0-(CAST(TRAFIk AS FLOAT) / CAST(TRAFIk_ANG AS FLOAT))) <=0.20 THEN 3
			WHEN ABS(1.0-(CAST(TRAFIk AS FLOAT) / CAST(TRAFIk_ANG AS FLOAT))) <=0.40 THEN 4
			ELSE 5 END AS TR_FLAG
	 , CASE WHEN a.QTY_GORKA = a.QTY_GORKA_ANG THEN 1 ELSE NULL END AS GORKA_FLAG
	 , CASE WHEN a.QTY_OHL = a.QTY_OHL_ANG THEN 1
			WHEN a.QTY_Z = a.QTY_Z_ANG THEN 2 ELSE NULL END AS BONETA_FLAG
	 , CASE WHEN a.SEASON = a.SEASON_ANG THEN 1 ELSE NULL END AS SEASON_FLAG
	 , CASE WHEN a.SUBFRMT_ID = a.SUBFRMT_ID_ANG THEN 1 
			WHEN a.FRMT_ID = a.FRMT_ID_ANG THEN 2
			ELSE NULL END AS SUBFRMT_FLAG
FROM REPORTS.dbo.T_KG_EXCEL AS a;

GO


